config/routes.rb
Rails.application.routes.draw do
  root 'producto#index'
  get 'producto/nuevo'
  post 'producto/crear'
  get 'producto/:id/editar', to:'producto#editar', as:'producto_editar'
  patch 'producto/:id', to:'producto#actualizar', as:'producto_actualizar'
  delete 'producto/:id', to:'producto#eliminar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/producto_controller.rb
class ProductoController < ApplicationController
  def index
    @objProductos = Producto.all
  end

  # Acciones para la acción nuevo
  def nuevo
    @objProducto = Producto.new
  end
  def crear
    @objProducto = Producto.new(params[:producto].permit(:categoria, :nombre, :precio, :precio_venta))
    @objProducto.save
    redirect_to root_path 
  end
  def editar
    @objProducto = Producto.find(params[:id])
  end
  def actualizar
    @objProducto = Producto.find(params[:id])
    @objProducto.update(params[:producto].permit(:categoria, :nombre, :precio, :precio_venta))
    redirect_to root_path 
  end 
  def eliminar
    @objProducto = Producto.find(params[:id])
    @objProducto.destroy
    redirect_to root_path 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/producto_helper.rb
module ProductoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTareaMantenimiento</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid bg-dark ">
      <div class="container pt-5">
        <div class="row">
          <div class="col">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/producto/editar.html.erb
<h1>Editar Producto</h1>
<%= form_for @objProducto, url:producto_actualizar_path do |form| %>

    <%= form.label :Categoria %>
    <%= form.text_field :categoria %>

    <%= form.label :Nombre %>
    <%= form.text_field :nombre %>

    <%= form.label  :Precio %>
    <%= form.text_field :precio %>

    <%= form.label :"Precio de venta" %>
    <%= form.text_field :precio_venta %>


<%= form.submit "Editar producto" %>


<% end %>

app/views/producto/index.html.erb
<h1 class="mt-3 mb-3">Listado de productos</h1>
<table class="table table-striped table-dark table-bordered">
        <thead>
            <tr>
                <th>Categoria</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Precio de venta</th>
                <th>Acciones</th>
            </tr>            
        </thead>
        <tbody>            
            <% @objProductos.each do |item| %>
                <tr>
                    <td><%= item.categoria %></td>
                    <td><%= item.nombre %></td>
                    <td><%= item.precio %></td>
                    <td><%= item.precio_venta %>        </td>
                    <td> 
                        <%= link_to 'editar', producto_editar_path(item), class: "btn btn-warning" %>
                        <%= link_to 'eliminar', {action: :eliminar, id: item.id}, method: :delete, data:{confirm:'Desea eliminar el producto?'} , class: "btn btn-danger" %>
                    </td>
                </tr>
            <% end %>            
        </tbody>
</table>

<%= link_to 'Nuevo producto', producto_nuevo_path, class: "btn btn-success" %>

app/views/producto/nuevo.html.erb
<h1 class="mt-3 mb-3">Nuevo Producto</h1>
<%= form_for @objProducto , :html => {class: 'needs-validation', data: { bar: 'baz' } },   url:producto_crear_path do |form|%> 
    <div class="form-row">
        <div class="col">
                <div class="form-group">
                        <%= form.label :Categoria %>
                        <%= form.text_field :categoria, class:"form-control", placeholder: "Ingresar categoria" %>
                    </div>
        </div>    
        <div class="col">
                <div class="form-group">
                        <%= form.label :Nombre %>
                        <%= form.text_field :nombre, class:"form-control", placeholder: "Ingresar nombre" %>
                    </div>
        </div>    
    </div>

    <div class="form-row">
            <div class="col">
                    <div class="form-group">
                            <%= form.label  :Precio %>
                            <%= form.text_field :precio, class:"form-control", placeholder: "Ingresar precio" %>
                        </div>
            </div>    
            <div class="col">
                    <div class="form-group">
                            <%= form.label :"Precio de venta" %>
                            <%= form.text_field :precio_venta, class:"form-control", placeholder: "Ingresar Precio de venta" %>
                        </div>
            </div>    
        </div>
   
<%= form.submit "Crear producto", class: "btn btn-primary" %>

<% end %>

<script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
        </script>